spring:
  datasource:
    username: root
    password: admin123
    url: jdbc:mysql://localhost:3306/scientific_research?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat,wall
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  mvc:
    format:
      date: yyyy-MM-dd
    static-path-pattern: /static/**
  mail:
    username: 1776557392@qq.com
    password: cxqofcvolzgabecj
    host: smtp.qq.com
    properties.mail.smtp.ssl.enable: true
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.sicnu.pojo
  mapper-locations: classpath:com/sicnu/dao/*.xml