spring:
  mvc:
    format:
      date: yyyy-MM-dd
    static-path-pattern: /static/**
  mail:
    username: 1776557392@qq.com
    password: cxqofcvolzgabecj
    host: smtp.qq.com
    properties.mail.smtp.ssl.enable: true
  thymeleaf:
    cache: false

mybatis:
  type-aliases-package: com.sicnu.pojo
  mapper-locations: classpath:com/sicnu/dao/*.xml